pipeline:
  build:
    image: node:8-alpine
    commands:
      - npm install
  publish:
    image: plugins/docker
    repo: registry.danibiro.com/dani/dani
    tags: [ latest ]
    secrets: [ docker_username, docker_password ]
    registry: registry.danibiro.com
